apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-api
  labels:
    app: meeting-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meeting-api
  template:
    metadata:
      labels:
        app: meeting-api
    spec:
      containers:
      - name: api
        image: crashbytes/meeting-transcription:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai-api-key
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: huggingface-token
        - name: QDRANT_URL
          value: "http://qdrant-service:6333"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: POSTGRES_DB
          value: "meeting_transcription"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: meeting-api-service
  labels:
    app: meeting-api
spec:
  type: LoadBalancer
  selector:
    app: meeting-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  - protocol: TCP
    port: 443
    targetPort: 8000
    name: https
